from typing import Mapping, Tuple, Callable

# Mapping data structure (dict)
# key: Source csv name (string)
# value: ((Dest csv name1, name2), mapping fn: string -> (tuple of strings)}



copy = lambda x: (x,)
numeric = lambda x: (float(x) if x != '' else None,)
numeric_zero_null = lambda x: (float(x) if x != '0' else None,)

# returns tuple of (name, variety, extra_desc)
# from NUTTAB Food Name
def process_name(food_name: str) -> Tuple[str, str, str]:
    split = food_name.split(", ")
    if len(split) == 1:
        name = food_name
        variety = ""
        extra_desc = ""
    else:
        name = split[0]
        variety = split[1]
        extra_desc = ", ".join(split[2:])

    return (name, variety, extra_desc)

food_details_mappings: Mapping[str, Tuple[Tuple[str, ...], Callable[[str], Tuple[str, ...]]]] = {
    "Public Food Key": (("NUTTAB index",), copy), 
    "Food Profile ID": ((), None), 
    "Derivation": (("data_source",), copy), 
    #"Name": ((), None), 
    "Name": (("name", "variety", "extra_desc"), process_name), 
    "Description": (("notes",), copy), 
    "Scientific Name": ((), None), 
    "Sampling details": (("data_notes",), copy), 
    "Nitrogen Factor": ((), None), 
    "Fat Factor": ((), None), 
    "Specific Gravity": (("density",), numeric_zero_null), 
    "Analysed portion": ((), None), 
    "Unanalysed portion": ((), None), 
    "Classification ID": ((), None), 
    "Classification Name": ((), None),
}


nutrition_mappings = {
    "Public Food Key": (("NUTTAB index",), copy), 
    "Classification": ((), None), 
    #"Food Name": (("name", "variety", "extra_desc"), process_name), 
    "Food Name": ((), None),
    "Energy, with dietary fibre": (("energy",), numeric), 
    "Energy, without dietary fibre": ((), None), 
    "Moisture (water)": (("water",), numeric), 
    "Protein": (("protein",), numeric), 
    "Nitrogen": ((), None), 
    "Total fat": (("fat",), numeric), 
    "Ash": ((), None), 
    "Total dietary fibre": (("fibre",), numeric), 
    "Alcohol": (("alcohol",), None), 
    "Fructose": ((), None), 
    "Glucose": ((), None), 
    "Sucrose": ((), None), 
    "Maltose": ((), None), 
    "Lactose": ((), None), 
    "Galactose": ((), None), 
    "Maltotriose": ((), None), 
    "Total sugars": (("sugar",), numeric), 
    "Added sugars": ((), None), 
    "Free sugars": ((), None), 
    "Starch": (("starch",), numeric), 
    "Dextrin": ((), None), 
    "Glycerol": ((), None), 
    "Glycogen": ((), None), 
    "Inulin": ((), None), 
    "Mannitol": ((), None), 
    "Maltodextrin": ((), None), 
    "Oligosaccharides": ((), None), 
    "Raffinose": ((), None), 
    "Stachyose": ((), None), 
    "Sorbitol": ((), None), 
    "Resistant starch": ((), None), 
    "Available carbohydrate, without sugar alcohols": (("carbohydrate",),
        numeric), 
    # TODO have to subtract carbohydrate without sugar alcohols
    "Available carbohydrate, with sugar alcohols": (("sugar_alcohol",), numeric), 
    "Acetic acid": ((), None), 
    "Citric acid": ((), None), 
    "Fumaric acid": ((), None), 
    "Lactic acid": ((), None), 
    "Malic acid": ((), None), 
    "Oxalic acid": ((), None), 
    "Propionic acid": ((), None), 
    "Quinic acid": ((), None), 
    "Succinic acid": ((), None), 
    "Tartaric acid": ((), None), 
    "Aluminium (Al)": ((), None), 
    "Antimony (Sb)": ((), None), 
    "Arsenic (As)": ((), None), 
    "Cadmium (Cd)": ((), None), 
    "Calcium (Ca)": (("calcium",), None), 
    "Chromium (Cr)": ((), None), 
    "Chloride (Cl)": ((), None), 
    "Cobalt (Co)": ((), None), 
    "Copper (Cu)": ((), None), 
    "Fluoride (F)": ((), None), 
    "Iodine (I)": ((), None), 
    "Iron (Fe)": (("iron",), None), 
    "Lead (Pb)": ((), None), 
    "Magnesium (Mg)": ((), None), 
    "Manganese (Mn)": ((), None), 
    "Mercury (Hg)": ((), None), 
    "Molybdenum (Mo)": ((), None), 
    "Nickel (Ni)": ((), None), 
    "Phosphorus (P)": ((), None), 
    "Potassium (K)": (("potassium",), None), 
    "Selenium (Se)": ((), None), 
    "Sodium (Na)": (("sodium",), None), 
    "Sulphur (S)": ((), None), 
    "Tin (Sn)": ((), None), 
    "Zinc (Zn)": ((), None), 
    "Retinol (preformed vitamin A)": ((), None), 
    "Alpha-carotene": ((), None), 
    "Beta-carotene": ((), None), 
    "Cryptoxanthin": ((), None), 
    "Beta-carotene equivalents (provitamin A)": ((), None), 
    "Vitamin A retinol equivalents": ((), None), 
    "Lutein": ((), None), 
    "Lycopene": ((), None), 
    "Xanthophyl": ((), None), 
    "Thiamin (B1)": ((), None), 
    "Riboflavin (B2)": ((), None), 
    "Niacin (B3)": ((), None), 
    "Niacin derived from tryptophan": ((), None), 
    "Niacin derived equivalents": ((), None), 
    "Pantothenic acid (B5)": ((), None), 
    "Pyridoxine (B6)": ((), None), 
    "Biotin (B7)": ((), None), 
    "Cobalamin (B12)": ((), None), 
    "Folate, natural": ((), None), 
    "Folic acid": ((), None), 
    "Total folates": ((), None), 
    "Dietary folate equivalents": ((), None), 
    "Vitamin C": (("vitamin_c"), None), 
    "Cholecalciferol (D3)": ((), None), 
    "Ergocalciferol (D2)": ((), None), 
    "25-hydroxy cholecalciferol (25-OH D3": ((), None), 
    "25-hydroxy ergocalciferol (25-OH D2)": ((), None), 
    "Vitamin D3 equivalents": ((), None), 
    "Alpha tocopherol": ((), None), 
    "Alpha tocotrienol": ((), None), 
    "Beta tocopherol": ((), None), 
    "Beta tocotrienol": ((), None), 
    "Delta tocopherol": ((), None), 
    "Delta tocotrienol": ((), None), 
    "Gamma tocopherol": ((), None), 
    "Gamma tocotrienol": ((), None), 
    "Vitamin E": ((), None), 
    "Total saturated fatty acids": (("saturated_fat",), numeric), 
    "Total monounsaturated fatty acids": (("monounsaturated_fat",), numeric), 
    "Other polyunsaturated fatty acids": ((), None), 
    "Total polyunsaturated fatty acids": (("polyunsaturated_fat",), numeric), 
    "Total long chain omega 3 fatty acids": (("omega_3",), None), 
    "Total undifferentiated fatty acids": ((), None), 
    "Total trans fatty acids": (("trans_fat",), numeric), 
    "Caffeine": (("caffeine",), numeric), 
    "Cholesterol": ((), None), 
    "Tryptophan": ((), None), 
    "Alanine": ((), None), 
    "Arginine": ((), None), 
    "Aspartic acid": ((), None), 
    "Cystine plus cysteine": ((), None), 
    "Glutamic acid": ((), None), 
    "Glycine": ((), None), 
    "Histidine": ((), None), 
    "Isoleucine": ((), None), 
    "Leucine": ((), None), 
    "Lysine": ((), None), 
    "Methionine": ((), None), 
    "Phenylalanine": ((), None), 
    "Proline": ((), None), 
    "Serine": ((), None), 
    "Threonine": ((), None), 
    "Tyrosine": ((), None), 
    "Valine": ((), None), 
}
